server.port=8081
politikum.db.path=/opt/politikum-data/politikum.sqlite
politikum.news.path=/opt/politikum-data/NEWS.md
politikum.profile-img-dir=/opt/politikum-data/profile_images
politikum.admin-token=1bf55a3f0bd42343ba12efbed229d5ca902e77f449672266acc3916435718cab