server.port=8081
politikum.db.path=/opt/politikum-data/politikum.sqlite
politikum.news.path=/opt/politikum-data/NEWS.md
politikum.profile-img-dir=/opt/politikum-data/profile_images
politikum.admin-token=${POLITIKUM_ADMIN_TOKEN:}
